[DEV-11867] Add Titles and Headers to Storybook
prezly/theme-kit-js pull request #416
Opened 2023-10-27 09:15 UTC by fgyimah

2023-10-30 14:01 UTC, oleg-semyonov requested changes

2023-10-30 14:01 UTC, oleg-semyonov commented on packages/ui/src/components/StoryShareLinks/StoryShareLinks.stories.tsx
> +import { StoryShareLinks } from '.';
Better to not re-import from index file and use direct import from the component file

2023-10-30 14:21 UTC, fgyimah commented on packages/ui/src/components/StoryShareLinks/StoryShareLinks.tsx
> +            </a>
I added them from the icons on the design system in figma file (they will be exported so other themes may use)

2023-10-30 16:36 UTC, fgyimah commented on packages/ui/package.json
> +      "require": "./build/index.umd.js"
Updated

2023-10-30 16:36 UTC, fgyimah commented on packages/ui/src/components/Breadcrumbs/components/Breadcrumb.tsx
> +            </Link>
Updated

2023-10-30 16:37 UTC, fgyimah commented on packages/ui/src/icons/index.ts
> +export { default as AppleIcon } from './apple.svg?react';
Removed the `Icon` suffix

2023-10-30 16:37 UTC, fgyimah commented on packages/ui/tsconfig.eslint.json
> +  "include": ["./src", "./@types/*", "next-env.d.ts", "tailwind.config.js", "vite.config.js"]
Fixed

2023-10-30 16:37 UTC, fgyimah commented on packages/ui/vite.config.js
> +            formats: ['es', 'umd'],
Updated

2023-10-30 16:37 UTC, fgyimah commented on packages/ui/src/components/StoryShareLinks/types.ts
> +export type ShareableSocialNetwork = Exclude<SocialNetwork, 'instagram' | 'tiktok' | 'youtube'>;
Rechecked, they still don't support

2023-10-31 08:05 UTC, oleg-semyonov approved these changes
Great work! 👍🏻

2023-10-31 08:05 UTC, oleg-semyonov commented on packages/ui/src/components/StoryShareLinks/types.ts
> +export type ShareableSocialNetwork = Exclude<SocialNetwork, 'instagram' | 'tiktok' | 'youtube'>;
Could you update the date to October 2023 then, so that we know that this statement is still relevant? 🙏🏻

2023-10-31 08:08 UTC, fgyimah commented on packages/ui/src/components/StoryShareLinks/types.ts
> +export type ShareableSocialNetwork = Exclude<SocialNetwork, 'instagram' | 'tiktok' | 'youtube'>;
https://github.com/prezly/theme-kit-js/pull/416/commits/c03da49966906567a370f340e1e5183fe4ec2f06

2023-10-31 08:13 UTC, merged